#!/bin/sh

# This shell script builds the complete pdf2htmlEX application LOCALLY
# (It does not create the AppImage or Docker images)

# Adjust the following two environment variables to suit your needs
#
export UNATTENDED="-y"
export MAKE_PARALLEL="-j $(nproc)"

export SOURCE_FOLDER="$(pwd)"
export PLATFORM="$(uname -r | sed 's/.*\(amzn[12]\).*/\1/')"
export CMAKE="cmake3"

if [ "$PLATFORM" == "amzn1" ] ; then
  export GCC="gcc72"
  export GPP="gcc72-c++"
  export PYTHON_PIP3="python36-pip"
  export PIP3="pip-3.6"
else
  export GCC="gcc"
  export GPP="gcc-c++"
  export PYTHON_PIP3="python3-pip"
  export PIP3="pip3"
fi

# choose one of the following...
#
# export PDF2HTMLEX_BRANCH="<<YourTagHereWithNoSpaces>>"
# export PDF2HTMLEX_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
export PDF2HTMLEX_BRANCH="master"

# The following environment variable determines where the poppler,
# poppler-data, fontforge and pdf2htmlEX packages are installed.
# CHANGE IT TO SUIT YOUR NEEDS:
#
export PDF2HTMLEX_PREFIX=/usr

set -ev

################
# do the build
cd "$(dirname `dirname $0`)"
sudo chmod -R a+w .

./buildScripts/versionEnvs

./buildScripts/reportEnvs

./buildScripts/getBuildToolsAmzn

./buildScripts/getDevLibrariesAmzn

./buildScripts/getPoppler

./buildScripts/buildPoppler

./buildScripts/getFontforge

./buildScripts/buildFontforge

./buildScripts/buildPdf2htmlEX

./buildScripts/installPdf2htmlEX
