#!/bin/sh

# This shell script automates getting the required build tools (yum install)

# set the shell environment variable 'UNATTENDED' to '-y' for
# unattended use (for example in the .travis.yml script)

echo ""
echo "-------------------------------------------------------------------"
echo "INSTALLING Build Tools (using YUM)"
echo "  (UNATTENDED: [$UNATTENDED])"
echo "-------------------------------------------------------------------"
echo ""

set -ev

sudo yum update -y
sudo yum $UNATTENDED install     \
  sudo                           \
  wget                           \
  git                            \
  pkgconfig                      \
  ruby                           \
  autoconf                       \
  libtool                        \
  cmake3                         \
  make                           \
  gcc72                          \
  gcc72-c++                      \
  gettext                        \
  java-1.8.0-openjdk-headless    \
  jq

