#!/bin/sh

# This shell script gets and unpacks the latest fontforge AppImage

# source buildScripts/reSourceVersionEnvs
. buildScripts/reSourceVersionEnvs

echo ""
echo "-------------------------------------------------------------------"
echo "GETTING FontForge sources (using curl)"
echo "  (FONTFORGE_VERSION: [$FONTFORGE_VERSION])"
echo "-------------------------------------------------------------------"
echo ""

set -ev

export FOLDER=fontforge
rm -rf $FOLDER
mkdir -p $FOLDER
curl -L https://github.com/fontforge/fontforge/archive/$FONTFORGE_VERSION.tar.gz \
  | tar zx --strip-components=1 -C $FOLDER
