#!/bin/sh

# This shell script gets and unpacks the latest Poppler source code

# source buildScripts/reSourceVersionEnvs
. buildScripts/reSourceVersionEnvs

echo ""
echo "-------------------------------------------------------------------"
echo "GETTING Poppler source code (using curl)"
echo "  (POPPLER_VERSION: [$POPPLER_VERSION])"
echo "-------------------------------------------------------------------"
echo ""

set -ev

echo "Getting poppler version: $POPPLER_VERSION"

export FOLDER=poppler
rm -rf $FOLDER
mkdir -p $FOLDER
curl -L https://poppler.freedesktop.org/poppler-$POPPLER_VERSION.tar.xz \
  | tar xJ --strip-components=1 -C $FOLDER

echo "Getting poppler-data version: $POPPLER_DATA_VERSION"

export FOLDER=poppler-data
rm -rf $FOLDER
mkdir -p $FOLDER
curl -L https://poppler.freedesktop.org/poppler-data-$POPPLER_DATA_VERSION.tar.gz \
  | tar zx --strip-components=1 -C $FOLDER
